# /config/packages/knp_snappy.yaml
knp_snappy:
  process_timeout: 60
  pdf: 
    enabled: true
    binary: "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
    options:
      []
  temporary_folder: "%kernel.cache_dir%\\snappy"