<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '303b75b314d614af4592ebb02e166e13',
  'DATABASE_URL' => 'mysql://root:mister@127.0.0.1:3306/agenda?serverVersion=5.7',
  'MAILER_DSN' => 'sendgrid+smtp://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@default',
);
