
ALTER TABLE contrato ADD fecha_compromiso DATE DEFAULT NULL;
ALTER TABLE contrato ADD ultima_funcion VARCHAR(255) DEFAULT NULL, ADD q_mov INT DEFAULT NULL;
ALTER TABLE cobranza ADD fecha DATE DEFAULT NULL;

ALTER TABLE cobranza DROP FOREIGN KEY FK_AE20EF3D6A7CF079;
DROP INDEX IDX_AE20EF3D6A7CF079 ON cobranza;
ALTER TABLE cobranza ADD contrato_id INT NOT NULL, CHANGE funcion_id funcion_id INT DEFAULT NULL, CHANGE respuesta_id respuesta_id INT DEFAULT NULL, CHANGE fecha_compromiso fecha_compromiso DATETIME DEFAULT NULL, CHANGE is_nulo is_nulo TINYINT(1) DEFAULT NULL, CHANGE fecha fecha DATE DEFAULT NULL;
ALTER TABLE cobranza ADD CONSTRAINT FK_AE20EF3D70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id);
CREATE INDEX IDX_AE20EF3D70AE7BF1 ON cobranza (contrato_id);

ALTER TABLE pago_tipo ADD is_boucher TINYINT(1) DEFAULT NULL;

CREATE TABLE lotes (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(50) NOT NULL, estado TINYINT(1) NOT NULL, INDEX IDX_7BDBF5EC521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE lotes ADD CONSTRAINT FK_7BDBF5EC521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id);

ALTER TABLE cuenta ADD vigencia_contratos INT DEFAULT NULL;

ALTER TABLE contrato ADD folio VARCHAR(255) DEFAULT NULL;

update contrato set folio=id;
