CREATE TABLE pago_cuotas (id INT AUTO_INCREMENT NOT NULL, pago_id INT NOT NULL, cuota_id INT NOT NULL, monto INT NOT NULL, INDEX IDX_75D1048763FB8380 (pago_id), INDEX IDX_75D104876A7CF079 (cuota_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE pago_cuotas ADD CONSTRAINT FK_75D1048763FB8380 FOREIGN KEY (pago_id) REFERENCES pago (id);
ALTER TABLE pago_cuotas ADD CONSTRAINT FK_75D104876A7CF079 FOREIGN KEY (cuota_id) REFERENCES cuota (id);

CREATE TABLE cuenta_corriente (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE pago ADD cuenta_corriente_id INT NOT NULL, ADD fecha_ingreso DATE NOT NULL, ADD ncomprobante VARCHAR(255) NOT NULL;
ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E1FB75A3B FOREIGN KEY (cuenta_corriente_id) REFERENCES cuenta_corriente (id);
CREATE INDEX IDX_F4DF5F3E1FB75A3B ON pago (cuenta_corriente_id);
ALTER TABLE pago ADD comprobante LONGTEXT NOT NULL;

ALTER TABLE pago ADD usuario_anulacion_id INT DEFAULT NULL, ADD anulado TINYINT(1) DEFAULT NULL, ADD fecha_anulacion DATETIME DEFAULT NULL;
ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EBAF036CE FOREIGN KEY (usuario_anulacion_id) REFERENCES usuario (id);
CREATE INDEX IDX_F4DF5F3EBAF036CE ON pago (usuario_anulacion_id);

ALTER TABLE contrato ADD is_finalizado TINYINT(1) DEFAULT NULL;

Macarrona069


ALTER TABLE `pago` CHANGE `boleta` `boleta` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, CHANGE `ncomprobante` `ncomprobante` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;